INSERT INTO oa.sys_users (USERNAME, USER_TRUE_NAME, PASSWORD, STATUS, PHOTO_PATH, MANAGER_ID) VALUES ('admin', '管理员', '21232F297A5', 1, null, null);
INSERT INTO oa.sys_users (USERNAME, USER_TRUE_NAME, PASSWORD, STATUS, PHOTO_PATH, MANAGER_ID) VALUES ('zengling', '曾凌', 'E10ADC3949B', 1, '', null);
INSERT INTO oa.sys_users (USERNAME, USER_TRUE_NAME, PASSWORD, STATUS, PHOTO_PATH, MANAGER_ID) VALUES ('xiaohuihui', '小辉辉', 'E10ADC3949B', 1, '', 2);
INSERT INTO oa.sys_users (USERNAME, USER_TRUE_NAME, PASSWORD, STATUS, PHOTO_PATH, MANAGER_ID) VALUES ('zhangchuang', '张创', 'E10ADC3949B', 1, '', null);
INSERT INTO oa.sys_users (USERNAME, USER_TRUE_NAME, PASSWORD, STATUS, PHOTO_PATH, MANAGER_ID) VALUES ('xiaolaji', '小垃圾1', '54A1E7B9265', 1, '', 4);
INSERT INTO oa.sys_users (USERNAME, USER_TRUE_NAME, PASSWORD, STATUS, PHOTO_PATH, MANAGER_ID) VALUES ('hrmanager', '吴建辉', 'E10ADC3949B', 1, '', null);
INSERT INTO oa.sys_users (USERNAME, USER_TRUE_NAME, PASSWORD, STATUS, PHOTO_PATH, MANAGER_ID) VALUES ('meetingmanager', '张李境', 'E10ADC3949B', 1, '', null);
INSERT INTO oa.sys_users (USERNAME, USER_TRUE_NAME, PASSWORD, STATUS, PHOTO_PATH, MANAGER_ID) VALUES ('vehiclemanager', '严新贵', 'E10ADC3949B', 1, '', null);